// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareSecrets.Models;

namespace ShareSecrets.Migrations
{
    [DbContext(typeof(ShareSecretsContext))]
    [Migration("20180908182853_mymig")]
    partial class mymig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("ShareSecrets.Models.Secret", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("NikName");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("Secret");
                });
#pragma warning restore 612, 618
        }
    }
}
